# Generated by Django 3.2.7 on 2023-09-15 17:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manage_post', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manage_post.article')),
                ('category_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manage_post.category')),
            ],
            options={
                'verbose_name': 'ArticleCategory',
                'verbose_name_plural': 'ArticleCategories',
            },
        ),
    ]
